import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import ThemeProvider from "./components/theme-provider"
import { ModeToggle } from "./components/mode-toggle";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children } : {children: React.ReactNode}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className="min-h-screen font-sans bg-gradient-to-b from-chart-2 to-background text-white">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="p-4 flex justify-between items-center">
          <h1 className="text-xl font-bold">My Blog</h1>
          <nav className="space-x-4">
            <Link href="/" className="hover:underline">Home</Link>
            <Link href="/about" className="hover:underline">About</Link>
            <Link href="/blog" className="hover:underline">Blog</Link>
            <ModeToggle></ModeToggle>
          </nav>
        </header>
        <main className="p-6 max-w-3xl mx-auto">{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}